### ISSUE TITLE
Is sync-engine supports outlook sync?

### ISSUE THREAD

**Issue by zkryakgul** [closeio/sync-engine#15]
When i try to auth an outlook account like **"bin/inbox-auth some.account@outlook.com"** its says **"Nylas does not support the email provider"**. Is there any trick for auth an outlook acount with sync-engine?

**Comment by jkemp101** [comment]
We do use it with Outlook accounts but don't really use the CLI commands very much so I'm not sure how they are going to react to them (we use the API for our integration). Perhaps trying setting the provider as `custom` to force regular imap. See [here](https://github.com/closeio/sync-engine/blob/5b937e70cbbac147b40bb5cdfbe7fc07b667bdcd/bin/inbox-auth#L29).

**Comment by zkryakgul** [comment]
Thanks for the response! Im started to using API too. Then it fixed! Thank you.
