### ISSUE TITLE
Possible engine for MailspringLibre?

### ISSUE THREAD

**Issue by lowercase00** [closeio/sync-engine#40]
Hi there.
I've tried using Mailspring, but had series errors with accounts "confusion" - mail sent from one account was being sent by another accounts. Mailspring has its sync engine written in C++ and closed source. As I read maintainers are looking for a new sync engine I was wondering if that could make sense.
Thanks !

**Comment by AlecRosenbaum** [comment]
Sorry, we have no knowledge of or affiliation with https://github.com/Foundry376/Mailspring or https://github.com/notpushkin/Mailspring-Libre. We run sync-engine alongside the other backend services that power [close.com](https://close.com).

I think you'll have to take this up with one of the maintainers of those repositories.
