### ISSUE TITLE
Run Nylas service for production?

### ISSUE THREAD

**Issue by zkryakgul** [closeio/sync-engine#42]
How can i run the Nylas service for production env in compose?

**Comment by jkemp101** [comment]
The `docker-compose.yml` file in this repo is used for testing and potentially dev environments but isn't necessarily for production use. Our infrastructure uses Kubernetes so we don't really have experience using Docker Compose in production for this service. But it shouldn't be too different than any other type of service with dependencies like Redis and MySQL.

**Comment by zkryakgul** [comment]
Actually i meant to be how to start nylas service for production env in container. Because in Dockerfile there is no process starting when container is become up. When i inspect your circle.ci config like you said running just testing stuffs. I tried the `bin/inbox-start` but its fails because of the in production env assuming the /etc/inboxapp exist and inbox as a installed lib.

**Comment by jkemp101** [comment]
Adding the following to the end of the Dockerfile will get it closer to being ready to startup. But you are going to need to modify the config files and do a bit of other configuration work to get it ready to be deployed in production. For instance, the Dockerfile sets everything up as root which I wouldn't recommend for production images.

```
RUN mkdir /etc/inboxapp
COPY etc/config-dev.json /etc/inboxapp/config.json
COPY etc/secrets-dev.yml /etc/inboxapp/secrets.yml
ENV PYTHONPATH=.
```

**Comment by zkryakgul** [comment]
Thanks for the answer. Thats exactly what i need.
