### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by philfreo** [closeio/sync-engine#48]
__Plan of Attack to get to Python 3.6__

1. Prep
    1. Consider some adhoc linting rules to help with the migration until we can use LintLizard with Py3
    3. Build and run tests in py2 and py3 images
    4. Review https://making.close.com/posts/python-3
    5. Consider if there are any additional metrics that could be added that would help identify issues during the conversion to py3
    5. Consider areas of the codebase not being used and determine if we should remove or guard them. Examples: email sending, contact sync, etc.
    6. Finish work needed to switch from the Vagrant dev environment to Docker. At a minimum update Readme with steps to get it started.
2. Upgrade dependencies to versions tested on at least PY3.6.
    1. High risk dependencies should be done by themselves. Low risk dependencies can be deployed in small batches.
    2. Remove unused dependencies
    3. Move to pypi/upstream versions
    4. Refactor requirements files
        1. Move `requirements_lint.txt` to `requirements/lint.txt`
        2. Split `requirements_frozen.txt` to `requirements/prod.txt` and `requirements/tests.txt`
        3. If needed there can also be a `requirements/dev.txt` for development environment dependencies
3. Futurize - If possible each of these are done on sections of the codebase and deployed to limit number of changes
    1. Stage 1 `futurize -w -n -1 -a -p -u "$@``"`
    2. Stage 2 `futurize -w -n -2 "$@``"`
4. Post Py3
    1. Add [LintLizard](https://github.com/closeio/lintlizard) 
    1. Remove `future` dependency
    2. Finish upgrading dependencies if needed
    3. Work on Py3.8 compatibility

**Comment by philfreo** [comment]
Is this all done / should we close?

**Comment by squeaky-pl** [comment]
Closing. Formatters / static analysis has now [separate issue](https://github.com/closeio/sync-engine/issues/311).
