### ISSUE TITLE
Reduce logging volume

### ISSUE THREAD

**Issue by jkemp101** [closeio/sync-engine#6]
Large Sync Engine clusters can produce an enormous volume of logs. https://github.com/closeio/nylas/pull/36 reduced this a bit but more work is needed to further reduce logging frequency. This may make it more difficult to troubleshoot some syncing issues so we could add the ability to enable per account debug logging.

**Comment by dggreenbaum** [comment]
This is significantly less important after moving to Loki. Loki ingests logs for ~15% of the cost of doing it in ES for the same log volume.
