### ISSUE TITLE
Use `pip-compile` from `pip-tools` to compile requirements

### ISSUE THREAD

**Issue by neob91-close** [closeio/sync-engine#982]
This will make package upgrades easier and safer. There is a script we already use for our other repositories, we should use that.

**Comment by wojcikstefan** [comment]
Or is it time to give [uv](https://docs.astral.sh/uv/) a shot?

**Comment by neob91-close** [comment]
It's a drop-in replacement for `pip-tools`'s `pip-compile`, isn't it? I'd rather separate these two endeavors.

**Comment by neob91-close** [comment]
Added here: https://github.com/closeio/sync-engine/pull/984
